"use strict";
const htwbAppUserStatus=document.getElementById("user-status"),htwbAppHeaderLogin=document.getElementById("header-login"),htwbAppHeaderLogout=document.getElementById("header-logout"),htwbAppLoginPanel=document.getElementById("login-panel"),htwbAppConnectedPanel=document.getElementById("connected-panel"),htwbAppTeamName=document.getElementById("team-name"),htwbAppManagerName=document.getElementById("manager-name"),htwbAppTeamId=document.getElementById("team-id"),htwbAppTeamLogo=document.getElementById("team-logo");
const HTWB_APP_TEAM_STORAGE_KEY="htwb_selected_team_id";let htwbAppAccountData=null,htwbAppSelectedTeam=null;
function htwbAppSafeLogoUrl(value){const raw=String(value||"").trim();if(!raw)return "";try{const u=new URL(raw,window.location.origin);return u.protocol==="https:"||u.protocol==="http:"?u.href:"";}catch{return "";}}
function htwbAppRenderTeamLogo(team){if(!htwbAppTeamLogo)return;htwbAppTeamLogo.hidden=true;htwbAppTeamLogo.removeAttribute("src");htwbAppTeamLogo.alt="";const url=htwbAppSafeLogoUrl(team?.logoUrl);if(!url)return;htwbAppTeamLogo.src=url;htwbAppTeamLogo.alt=team?.teamName?`${team.teamName} logo`:"Team logo";htwbAppTeamLogo.hidden=false;}
function htwbAppShowLoggedOut(){htwbAppAccountData=null;htwbAppSelectedTeam=null;if(htwbAppUserStatus)htwbAppUserStatus.textContent="Not connected";htwbAppRenderTeamLogo(null);if(htwbAppHeaderLogin)htwbAppHeaderLogin.hidden=false;if(htwbAppHeaderLogout)htwbAppHeaderLogout.hidden=true;if(htwbAppLoginPanel)htwbAppLoginPanel.hidden=false;if(htwbAppConnectedPanel)htwbAppConnectedPanel.hidden=true;}
function htwbAppGetSavedTeamId(){try{return localStorage.getItem(HTWB_APP_TEAM_STORAGE_KEY)||"";}catch{return "";}}
function htwbAppSaveTeamId(id){try{if(id)localStorage.setItem(HTWB_APP_TEAM_STORAGE_KEY,id);}catch{}}
function htwbAppFindTeam(id){return htwbAppAccountData?.teams?.find(t=>String(t.teamId)===String(id))||null;}
function htwbAppChooseInitialTeam(data){const teams=Array.isArray(data.teams)?data.teams:[];if(!teams.length)return null;return htwbAppFindTeam(htwbAppGetSavedTeamId())||htwbAppFindTeam(data.teamId)||teams[0];}
function htwbAppRenderSelectedTeam(team){if(!team){if(htwbAppTeamName)htwbAppTeamName.textContent="No managed team found";if(htwbAppTeamId)htwbAppTeamId.textContent="";if(htwbAppUserStatus)htwbAppUserStatus.textContent="Connected";htwbAppRenderTeamLogo(null);return;}htwbAppSelectedTeam=team;htwbAppSaveTeamId(team.teamId);window.dispatchEvent(new CustomEvent("htwb:team-selected",{detail:{teamId:team.teamId,teamName:team.teamName,logoUrl:team.logoUrl||""}}));if(htwbAppTeamName)htwbAppTeamName.textContent=team.teamName||"Hattrick team";htwbAppRenderTeamLogo(team);if(htwbAppTeamId)htwbAppTeamId.textContent=team.teamId?`TeamID: ${team.teamId}`:"";if(htwbAppUserStatus)htwbAppUserStatus.textContent=team.teamName||"Connected";}
function htwbAppRemoveTeamSelector(){document.getElementById("team-selector-wrapper")?.remove();}
function htwbAppCreateTeamSelector(teams){htwbAppRemoveTeamSelector();if(!Array.isArray(teams)||teams.length<=1||!htwbAppConnectedPanel)return;const w=document.createElement("div");w.id="team-selector-wrapper";w.className="team-selector-wrapper";const l=document.createElement("label");l.htmlFor="team-selector";l.textContent="Active team";const s=document.createElement("select");s.id="team-selector";s.className="team-selector";for(const team of teams){const o=document.createElement("option");o.value=team.teamId;o.textContent=`${team.teamName} - TeamID ${team.teamId}`;o.selected=String(team.teamId)===String(htwbAppSelectedTeam?.teamId);s.appendChild(o);}s.addEventListener("change",e=>{const t=htwbAppFindTeam(e.target.value);if(t)htwbAppRenderSelectedTeam(t);});w.append(l,s);htwbAppConnectedPanel.appendChild(w);}
function htwbAppShowLoggedIn(data){htwbAppAccountData=data;if(htwbAppHeaderLogin)htwbAppHeaderLogin.hidden=true;if(htwbAppHeaderLogout)htwbAppHeaderLogout.hidden=false;if(htwbAppLoginPanel)htwbAppLoginPanel.hidden=true;if(htwbAppConnectedPanel)htwbAppConnectedPanel.hidden=false;if(htwbAppManagerName)htwbAppManagerName.textContent=data.managerName?`Manager: ${data.managerName}`:"";htwbAppSelectedTeam=htwbAppChooseInitialTeam(data);htwbAppRenderSelectedTeam(htwbAppSelectedTeam);htwbAppCreateTeamSelector(data.teams);}
async function htwbAppLoadUser(){try{const r=await fetch("/api/me",{headers:{Accept:"application/json"}});if(r.status===401){htwbAppShowLoggedOut();return;}if(!r.ok)throw new Error(`Server returned ${r.status}`);htwbAppShowLoggedIn(await r.json());if(window.location.search.includes("login=success"))window.history.replaceState({},document.title,"/");}catch(e){console.error("Could not load Hattrick account:",e);htwbAppShowLoggedOut();}}
window.HTWikiBuilder={getSelectedTeamId(){return htwbAppSelectedTeam?.teamId||"";},getSelectedTeam(){return htwbAppSelectedTeam;},getManagedTeams(){return Array.isArray(htwbAppAccountData?.teams)?htwbAppAccountData.teams:[];}};
if(htwbAppTeamLogo)htwbAppTeamLogo.addEventListener("error",()=>{htwbAppTeamLogo.hidden=true;htwbAppTeamLogo.removeAttribute("src");htwbAppTeamLogo.alt="";});
htwbAppLoadUser();
