"use strict";
const htwbJerseyStatus=document.getElementById("jersey-status"),htwbJerseyLoad=document.getElementById("jersey-load-button"),htwbJerseyModeSection=document.getElementById("jersey-mode-section"),htwbJerseyPrepare=document.getElementById("jersey-prepare-button"),htwbJerseyResults=document.getElementById("jersey-results-section"),htwbJerseyResultsTitle=document.getElementById("jersey-results-title"),htwbJerseyResultsNote=document.getElementById("jersey-results-note"),htwbJerseyNewResults=document.getElementById("jersey-new-results"),htwbJerseyNewList=document.getElementById("jersey-new-list"),htwbJerseyNewEmpty=document.getElementById("jersey-new-empty"),htwbJerseyResetResults=document.getElementById("jersey-reset-results"),htwbJerseyChangeWrap=document.getElementById("jersey-change-table-wrap"),htwbJerseyChangeBody=document.getElementById("jersey-change-body"),htwbJerseyChangeEmpty=document.getElementById("jersey-change-empty"),htwbJerseyUnchangedList=document.getElementById("jersey-unchanged-list"),htwbJerseyUnchangedEmpty=document.getElementById("jersey-unchanged-empty");
let htwbJerseyTeamId="",htwbJerseyData=null,htwbJerseyLoading=false;
const htwbJerseyValidTeam=v=>/^\d+$/.test(String(v||""));
const htwbJerseyValidNumber=v=>Number.isInteger(Number(v))&&Number(v)>=1&&Number(v)<=99;
function htwbJerseySelectedTeam(){const id=window.HTWikiBuilder?.getSelectedTeamId?.();return htwbJerseyValidTeam(id)?String(id):htwbJerseyTeamId;}
function htwbJerseySetStatus(message,type=""){htwbJerseyStatus.textContent=message;htwbJerseyStatus.className="builder-status";if(type)htwbJerseyStatus.classList.add(`builder-status-${type}`)}
function htwbJerseyReset(teamId){htwbJerseyTeamId=htwbJerseyValidTeam(teamId)?String(teamId):"";htwbJerseyData=null;htwbJerseyModeSection.hidden=true;htwbJerseyResults.hidden=true;htwbJerseyLoad.disabled=!htwbJerseyTeamId||htwbJerseyLoading;htwbJerseySetStatus(htwbJerseyTeamId?"Ready. Click Load Roster.":"Waiting for team data.")}
function htwbJerseyDateValue(value){if(!value)return Number.POSITIVE_INFINITY;const raw=String(value).replace(" ","T");const date=new Date(/[zZ]|[+-]\d\d:?\d\d$/.test(raw)?raw:`${raw}Z`);return Number.isNaN(date.getTime())?Number.POSITIVE_INFINITY:date.getTime()}
function htwbJerseyOrdered(players){return [...players].sort((a,b)=>{const ad=htwbJerseyDateValue(a.arrivalDate),bd=htwbJerseyDateValue(b.arrivalDate);return ad-bd||Number(a.playerId)-Number(b.playerId)})}
function htwbJerseyPreferredNumbers(playerId){const id=Math.abs(Math.trunc(Number(playerId)||0)),remainder=id%11,start=remainder===0?11:remainder,result=[];for(let number=start;number<=99;number+=11)result.push(number);return result}
function htwbJerseyNextNumber(player,used){for(const number of htwbJerseyPreferredNumbers(player.playerId))if(!used.has(number))return number;for(let number=1;number<=99;number++)if(!used.has(number))return number;return null}
function htwbJerseyAssignNewOnly(players){const ordered=htwbJerseyOrdered(players),used=new Set(ordered.filter(p=>htwbJerseyValidNumber(p.playerNumber)).map(p=>Number(p.playerNumber))),assignments=[];for(const player of ordered){if(htwbJerseyValidNumber(player.playerNumber))continue;const number=htwbJerseyNextNumber(player,used);if(number===null)throw new Error("No jersey numbers are available from 1 through 99.");used.add(number);assignments.push({...player,newNumber:number})}return assignments}
function htwbJerseyResetAll(players){const ordered=htwbJerseyOrdered(players),used=new Set(),rows=[];for(const player of ordered){const newNumber=htwbJerseyNextNumber(player,used);if(newNumber===null)throw new Error("No jersey numbers are available from 1 through 99.");used.add(newNumber);rows.push({...player,newNumber})}return {changed:rows.filter(p=>!htwbJerseyValidNumber(p.playerNumber)||Number(p.playerNumber)!==p.newNumber),unchanged:rows.filter(p=>htwbJerseyValidNumber(p.playerNumber)&&Number(p.playerNumber)===p.newNumber)} }
function htwbJerseyMode(){return document.querySelector('input[name="jersey-mode"]:checked')?.value||"new"}
function htwbJerseyClearResults(){htwbJerseyNewList.innerHTML="";htwbJerseyChangeBody.innerHTML="";htwbJerseyUnchangedList.innerHTML="";htwbJerseyNewEmpty.hidden=true;htwbJerseyChangeEmpty.hidden=true;htwbJerseyUnchangedEmpty.hidden=true}
function htwbJerseyRenderNew(assignments){htwbJerseyClearResults();htwbJerseyNewResults.hidden=false;htwbJerseyResetResults.hidden=true;htwbJerseyResultsTitle.textContent="Jersey Numbers";htwbJerseyResultsNote.textContent="Only players without a current jersey number are listed. Existing roster numbers remain unchanged.";if(!assignments.length)htwbJerseyNewEmpty.hidden=false;for(const p of assignments){const li=document.createElement("li");li.textContent=`#${p.newNumber} ${p.name}`;htwbJerseyNewList.append(li)}htwbJerseyResults.hidden=false}
function htwbJerseyRenderReset(result){htwbJerseyClearResults();htwbJerseyNewResults.hidden=true;htwbJerseyResetResults.hidden=false;htwbJerseyResultsTitle.textContent="Full Roster Reassignment";htwbJerseyResultsNote.textContent="Make the changes listed below. Players in Unchanged can be skipped.";htwbJerseyChangeWrap.hidden=!result.changed.length;htwbJerseyChangeEmpty.hidden=Boolean(result.changed.length);for(const p of result.changed){const tr=document.createElement("tr"),name=document.createElement("td"),old=document.createElement("td"),next=document.createElement("td");name.textContent=p.name;old.textContent=htwbJerseyValidNumber(p.playerNumber)?String(Number(p.playerNumber)):"—";next.textContent=String(p.newNumber);old.className=next.className="number";tr.append(name,old,next);htwbJerseyChangeBody.append(tr)}if(!result.unchanged.length)htwbJerseyUnchangedEmpty.hidden=false;for(const p of result.unchanged){const li=document.createElement("li");li.textContent=`#${p.newNumber} ${p.name}`;htwbJerseyUnchangedList.append(li)}htwbJerseyResults.hidden=false}
function htwbJerseyPrepareNumbers(){if(!htwbJerseyData?.players?.length)return;try{if(htwbJerseyMode()==="reset")htwbJerseyRenderReset(htwbJerseyResetAll(htwbJerseyData.players));else htwbJerseyRenderNew(htwbJerseyAssignNewOnly(htwbJerseyData.players));htwbJerseyResults.scrollIntoView({behavior:"smooth",block:"start"})}catch(error){htwbJerseySetStatus(error.message||"Could not prepare jersey numbers.","error")}}
async function htwbJerseyLoadRoster(){const teamId=htwbJerseySelectedTeam();if(!htwbJerseyValidTeam(teamId)||htwbJerseyLoading)return;htwbJerseyLoading=true;htwbJerseyLoad.disabled=true;htwbJerseySetStatus("Loading current roster from Hattrick...");try{const response=await fetch(`/api/jersey?teamId=${encodeURIComponent(teamId)}`,{headers:{Accept:"application/json"}}),data=await response.json();if(!response.ok)throw new Error(data.error||`Server returned ${response.status}`);if(htwbJerseySelectedTeam()!==teamId)return;htwbJerseyData=data;htwbJerseyModeSection.hidden=false;htwbJerseyResults.hidden=true;htwbJerseySetStatus(`Loaded ${data.players.length} players for ${data.teamName||`TeamID ${teamId}`}.`,"success");htwbJerseyModeSection.scrollIntoView({behavior:"smooth",block:"start"})}catch(error){htwbJerseySetStatus(error.message||"Could not load roster data.","error")}finally{htwbJerseyLoading=false;htwbJerseyLoad.disabled=!htwbJerseyValidTeam(htwbJerseySelectedTeam())}}
htwbJerseyLoad?.addEventListener("click",htwbJerseyLoadRoster);htwbJerseyPrepare?.addEventListener("click",htwbJerseyPrepareNumbers);document.querySelectorAll('input[name="jersey-mode"]').forEach(r=>r.addEventListener("change",()=>{htwbJerseyResults.hidden=true}));window.addEventListener("htwb:team-selected",event=>htwbJerseyReset(event.detail?.teamId));setTimeout(()=>htwbJerseyReset(htwbJerseySelectedTeam()),0);
