"use strict";
const el=id=>document.getElementById(id),statusEl=el("lineup-status"),loadBtn=el("lineup-load-matches-button"),buildBtn=el("lineup-build-button"),matchSelect=el("lineup-match-select"),trainingSelect=el("lineup-selected-training"),formationSelect=el("lineup-selected-formation"),resultSections=[...document.querySelectorAll("[data-lineup-result-section]")];
let selectedTeamId="",fixtureData=null,sourceData=null,current=null,loading=false,trainingOverride="",formationOverride="";
const FORMATIONS=["5-5-0","5-4-1","5-3-2","5-2-3","4-5-1","4-4-2","4-3-3","3-5-2","3-4-3","2-5-3"];
const TRAININGS=[
{id:"keeper",name:"Keeper",skill:"keeper",skillLabel:"Keeper",requiredPlayers:2,ideal:1,eff:1,full:["GK"],partial:{}},
{id:"defending",name:"Defending",skill:"defending",skillLabel:"Defending",requiredPlayers:10,ideal:5,eff:1,full:["DEF"],partial:{}},
{id:"playmaking",name:"Playmaking",skill:"playmaking",skillLabel:"Playmaking",requiredPlayers:10,ideal:5,eff:1,full:["IM"],partial:{WG:.5}},
{id:"winger",name:"Winger",skill:"winger",skillLabel:"Winger",requiredPlayers:8,ideal:4,eff:1,full:["WG"],partial:{WB:.5}},
{id:"passing",name:"Passing",skill:"passing",skillLabel:"Passing",requiredPlayers:16,ideal:8,eff:1,full:["IM","WG","FW"],partial:{}},
{id:"scoring",name:"Scoring",skill:"scoring",skillLabel:"Scoring",requiredPlayers:6,ideal:3,eff:1,full:["FW"],partial:{}},
{id:"setPieces",name:"Set Pieces",skill:"setPieces",skillLabel:"Set Pieces",requiredPlayers:22,ideal:11,eff:1,full:["ALL"],partial:{}},
{id:"defendingExtended",name:"Defending (Defenders, Keepers + All Midfielders)",skill:"defending",skillLabel:"Defending",requiredPlayers:22,ideal:11,eff:.5,full:["GK","DEF","IM","WG"],partial:{}},
{id:"wingerExtended",name:"Winger (Winger + Attackers)",skill:"winger",skillLabel:"Winger",requiredPlayers:10,ideal:5,eff:.6,full:["WG","FW"],partial:{}},
{id:"passingExtended",name:"Passing (Defenders + All Midfielders)",skill:"passing",skillLabel:"Passing",requiredPlayers:20,ideal:10,eff:.8,full:["DEF","IM","WG"],partial:{}},
{id:"scoringSetPieces",name:"Scoring and Set Pieces",skill:"scoring",skillLabel:"Scoring",requiredPlayers:20,ideal:10,eff:.571,full:["DEF","IM","WG","FW"],partial:{},visualAll:true}
];
const MATCH_HIGH=new Set([1,2,3,7,50,51,61,62,80]),MATCH_LOW=new Set([4,5,8,9]);
const fmtNum=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,validTeam=v=>/^\d+$/.test(String(v||""));
function selectedTeam(){const v=window.HTWikiBuilder?.getSelectedTeamId?.();return validTeam(v)?String(v):selectedTeamId}
function setStatus(msg,type=""){statusEl.textContent=msg;statusEl.className="builder-status";if(type)statusEl.classList.add(`builder-status-${type}`)}
function setVisible(v){resultSections.forEach(s=>s.hidden=!v)}
function playerLabel(p){const n=Number(p.playerNumber);return `${Number.isInteger(n)&&n>0?`${n} · `:""}${p.name}`}
function formationParts(name){const [d,m,f]=name.split("-").map(Number);return {d,m,f}}
const DEF_SLOTS={2:[["LCD","RCD"]],3:[["LCD","CD","RCD"]],4:[["LWB","LCD","RCD","RWB"]],5:[["LWB","LCD","CD","RCD","RWB"]]};
const MID_SLOTS={2:[["LW","RW"],["LCM","RCM"]],3:[["LW","CM","RW"],["LCM","CM","RCM"]],4:[["LW","LCM","RCM","RW"]],5:[["LW","LCM","CM","RCM","RW"]]};
const FWD_SLOTS={0:[[]],1:[["CF"]],2:[["LF","RF"]],3:[["LF","CF","RF"]]};
function layouts(name){const {d,m,f}=formationParts(name),out=[];for(const ds of DEF_SLOTS[d]||[])for(const ms of MID_SLOTS[m]||[])for(const fs of FWD_SLOTS[f]||[])out.push(["GK",...ds,...ms,...fs]);return out}
function role(slot){if(slot==="GK")return"GK";if(["LCD","CD","RCD"].includes(slot))return"CD";if(["LWB","RWB"].includes(slot))return"WB";if(["LCM","CM","RCM"].includes(slot))return"IM";if(["LW","RW"].includes(slot))return"WG";if(["LF","CF","RF"].includes(slot))return"FW";return""}
function trainRole(r,t){if(t.full.includes("ALL"))return 1;if(t.full.includes(r))return 1;if(t.full.includes("DEF")&&["CD","WB"].includes(r))return 1;if(t.partial[r])return t.partial[r];return 0}
function layoutEffect(slots,t){return slots.reduce((sum,s)=>sum+trainRole(role(s),t),0)}
function bestEffect(name,t){return Math.max(...layouts(name).map(x=>layoutEffect(x,t)),0)}
function formationExp(name){return fmtNum(sourceData?.formationExperience?.[name],3)}
function expFactor(name,match){const xp=Math.max(3,Math.min(10,formationExp(name))),type=fmtNum(match?.matchType);if(MATCH_HIGH.has(type))return(13-xp)/10;if(MATCH_LOW.has(type)&&match?.trainingWeekPosition!=="none")return xp/10;return(13-xp)/10}
function trainingAverage(players,t){const values=players.filter(p=>!p.isCoach).map(p=>Number(p[t.skill])).filter(Number.isFinite).sort((a,b)=>b-a);if(values.length<t.requiredPlayers)return null;return values.slice(0,t.requiredPlayers).reduce((a,b)=>a+b,0)/t.requiredPlayers}
function coachTie(a,b){const coach=String(sourceData?.coachType||"").toLowerCase(),A=formationParts(a),B=formationParts(b);if(coach.includes("offensive"))return B.f-A.f||A.d-B.d;return B.d-A.d||A.f-B.f}
function matrix(players,match){const rows=[];for(const t of TRAININGS){const avg=trainingAverage(players,t);if(avg===null)continue;for(const name of FORMATIONS){const effective=bestEffect(name,t),util=t.ideal?effective/t.ideal:0,score=effective?expFactor(name,match)*(t.ideal/effective):Infinity,comb=score*avg/t.eff;rows.push({t,name,avg,effective,util,score,comb})}}rows.sort((a,b)=>a.comb-b.comb||coachTie(a.name,b.name)||TRAININGS.indexOf(a.t)-TRAININGS.indexOf(b.t)||FORMATIONS.indexOf(a.name)-FORMATIONS.indexOf(b.name));return rows}
function weeklyKey(match){const d=new Date(String(match?.matchDate||"").replace(" ","T")+(/[zZ]|[+-]\d\d:?\d\d$/.test(String(match?.matchDate||""))?"":"Z"));if(Number.isNaN(d.getTime()))return"";const day=d.getUTCDay(),hour=d.getUTCHours();let diff=(day-5+7)%7;if(day===5&&hour<6)diff=7;const friday=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()-diff,6));return `htwb_lineup_weekly_training:${selectedTeam()}:${friday.toISOString().slice(0,10).replaceAll("-","")}`}
function inheritedTraining(match){if(match?.trainingWeekPosition!=="second")return"";try{const saved=localStorage.getItem(weeklyKey(match));if(TRAININGS.some(t=>t.id===saved))return saved}catch{}const currentId=sourceData?.currentTraining?.lineupTrainingId;return TRAININGS.some(t=>t.id===currentId)?currentId:""}
function saveTraining(match,id){if(match?.trainingWeekPosition!=="first")return;try{localStorage.setItem(weeklyKey(match),id)}catch{}}
function formFactor(p,match){const f=fmtNum(p.form,5),type=fmtNum(match?.matchType);return MATCH_LOW.has(type)&&match?.trainingWeekPosition!=="none"?(10-f)/10:f/10}
function ratings(p,match){const form=.75+.5*formFactor(p,match),stam=.85+.3*(fmtNum(p.stamina,5)/10),mul=form*stam;const raw={GK:fmtNum(p.keeper)+.2*fmtNum(p.defending)+.08*fmtNum(p.setPieces),CD:fmtNum(p.defending)+.25*fmtNum(p.playmaking)+.25*fmtNum(p.passing),WB:.65*fmtNum(p.defending)+.55*fmtNum(p.winger)+.25*fmtNum(p.passing)+.1*fmtNum(p.playmaking),IM:fmtNum(p.playmaking)+.4*fmtNum(p.passing)+.25*fmtNum(p.defending)+.12*fmtNum(p.scoring),WG:fmtNum(p.winger)+.45*fmtNum(p.passing)+.35*fmtNum(p.playmaking)+.15*fmtNum(p.scoring),FW:fmtNum(p.scoring)+.35*fmtNum(p.passing)+.2*fmtNum(p.winger)+.1*fmtNum(p.playmaking)};Object.keys(raw).forEach(k=>raw[k]*=mul);raw.AVG=Object.values(raw).reduce((a,b)=>a+b,0)/6;return raw}
function eligibility(players,match){const eligible=[],excluded=[];for(const p of players){const reasons=[];if(p.isCoach)reasons.push("Coach");else{if(fmtNum(p.injuryLevel,-1)>0)reasons.push("Injured");if(fmtNum(p.cards,0)===3&&MATCH_HIGH.has(fmtNum(match?.matchType)))reasons.push("Suspended")}if(reasons.length)excluded.push({p,reasons});else eligible.push({...p,ratings:ratings(p,match)})}return {eligible,excluded}}
function chooseLayout(name,t,eligible){const opts=layouts(name);let best=opts[0];let bestScore=-Infinity;for(const slots of opts){const effect=layoutEffect(slots,t),roleStrength=slots.reduce((s,x)=>s+Math.max(...eligible.map(p=>p.ratings[role(x)]||0),0),0),score=effect*10000+roleStrength;if(score>bestScore){bestScore=score;best=slots}}return best}
function fillLineup(slots,t,eligible){const available=[...eligible],assignments=[];const ordered=[...slots].sort((a,b)=>trainRole(role(b),t)-trainRole(role(a),t)||["GK","CD","LCD","RCD","LWB","RWB","CM","LCM","RCM","LW","RW","CF","LF","RF"].indexOf(a)-["GK","CD","LCD","RCD","LWB","RWB","CM","LCM","RCM","LW","RW","CF","LF","RF"].indexOf(b));for(const slot of ordered){const r=role(slot);available.sort((a,b)=>(b.ratings[r]||0)-(a.ratings[r]||0)||Number(a.playerId)-Number(b.playerId));const p=available.shift();if(p)assignments.push({slot,player:p,rating:p.ratings[r],train:trainRole(r,t)})}return {assignments,remaining:available}}
function substitutes(remaining){const roles=["GK","CD","WB","IM","FW","WG","AVG"],out=[];const pool=[...remaining];for(const r of roles){pool.sort((a,b)=>(b.ratings[r]||0)-(a.ratings[r]||0)||Number(a.playerId)-Number(b.playerId));const p=pool.shift();if(p)out.push({role:r,player:p,rating:p.ratings[r]})}return out}
function captain(starters){if(!starters.length)return null;const sum=starters.reduce((s,p)=>s+fmtNum(p.experience),0);return [...starters].sort((a,b)=>{const A=((sum+fmtNum(a.experience))/12)*(1-((7-fmtNum(a.leadership))/20)),B=((sum+fmtNum(b.experience))/12)*(1-((7-fmtNum(b.leadership))/20));return B-A||fmtNum(b.experience)-fmtNum(a.experience)||fmtNum(b.leadership)-fmtNum(a.leadership)||Number(a.playerId)-Number(b.playerId)})[0]}
function setPieces(starters,assignments){const gk=assignments.find(a=>a.slot==="GK")?.player?.playerId;return starters.filter(p=>String(p.playerId)!==String(gk)).sort((a,b)=>fmtNum(b.setPieces)-fmtNum(a.setPieces)||fmtNum(b.experience)-fmtNum(a.experience)||Number(a.playerId)-Number(b.playerId))[0]||null}
function selectedMatch(){return fixtureData?.matches?.find(m=>String(m.matchId)===String(matchSelect.value))||fixtureData?.upcomingMatch||null}
function calculate(){const match=sourceData.upcomingMatch,players=sourceData.players||[],m=matrix(players,match);if(!m.length)throw new Error("No training and formation combination could be calculated.");let win=m[0],inherit=inheritedTraining(match);const requestedTraining=trainingOverride||inherit;if(requestedTraining){const candidates=m.filter(x=>x.t.id===requestedTraining);if(candidates.length)win=candidates[0]}if(formationOverride){const found=m.find(x=>x.t.id===win.t.id&&x.name===formationOverride);if(found)win=found}const elig=eligibility(players,match),layout=chooseLayout(win.name,win.t,elig.eligible),filled=fillLineup(layout,win.t,elig.eligible),subs=substitutes(filled.remaining),starters=filled.assignments.map(a=>a.player),cap=captain(starters),sp=setPieces(starters,filled.assignments);saveTraining(match,win.t.id);return {matrix:m,win,elig,layout,filled,subs,cap,sp,inherit}}
function td(text,cls=""){const x=document.createElement("td");x.textContent=text;if(cls)x.className=cls;return x}
function renderTables(calc){const tBody=el("lineup-training-table-body");tBody.innerHTML="";for(const t of TRAININGS){const avg=trainingAverage(sourceData.players||[],t),tr=document.createElement("tr");tr.append(td(t.name),td(t.skillLabel),td(t.requiredPlayers,"number"),td(avg===null?"—":avg.toFixed(2),"number"),td(`${(t.eff*100).toFixed(t.eff===1?0:1)}%`,"number"),td(t.id===calc.win.t.id?"Selected":avg===null?"Not enough players":"Available"));tBody.append(tr)}const fBody=el("lineup-formation-table-body");fBody.innerHTML="";for(const name of FORMATIONS){const row=calc.matrix.find(x=>x.t.id===calc.win.t.id&&x.name===name),tr=document.createElement("tr");if(!row)continue;tr.append(td(name),td(formationExp(name).toFixed(1),"number"),td(`${Math.round(row.util*100)}%`,"number"),td(`${row.effective.toFixed(1)} / ${row.t.ideal.toFixed(1)}`,"number"),td(Number.isFinite(row.score)?row.score.toFixed(3):"∞","number"),td(Number.isFinite(row.comb)?row.comb.toFixed(3):"∞","number"),td(name===calc.win.name?"Selected":"Available"));fBody.append(tr)}}
function renderSelectors(calc){trainingSelect.innerHTML="";TRAININGS.forEach(t=>{const o=document.createElement("option");o.value=t.id;o.textContent=t.name;o.selected=t.id===calc.win.t.id;trainingSelect.append(o)});trainingSelect.disabled=false;formationSelect.innerHTML="";FORMATIONS.forEach(name=>{const o=document.createElement("option");o.value=name;o.textContent=name;o.selected=name===calc.win.name;formationSelect.append(o)});formationSelect.disabled=false;el("lineup-selected-training-average").textContent=calc.win.avg.toFixed(2);el("lineup-selected-formation-experience").textContent=formationExp(calc.win.name).toFixed(1);el("lineup-selected-formation-utilization").textContent=`${Math.round(calc.win.util*100)}%`;el("lineup-selected-formation-score").textContent=calc.win.score.toFixed(3);el("lineup-selected-combination-score").textContent=calc.win.comb.toFixed(3);el("lineup-training-choice-note").textContent=calc.inherit&&!trainingOverride?"Inherited for this training week":trainingOverride?"Manager override":"Recommended automatically";el("lineup-formation-choice-note").textContent=formationOverride?"Manager override":"Recommended automatically"}
const pitchSlots=["GK","LWB","LCD","CD","RCD","RWB","LW","LCM","CM","RCM","RW","LF","CF","RF"];
function renderPitch(calc){const pitch=el("lineup-pitch");pitch.innerHTML="";const rows=[["GK"],["LWB","LCD","CD","RCD","RWB"],["LW","LCM","CM","RCM","RW"],["LF","CF","RF"]],map=new Map(calc.filled.assignments.map(a=>[a.slot,a]));for(const rowSlots of rows){const row=document.createElement("div");row.className="pitch-row";if(rowSlots.length===1)row.style.gridTemplateColumns="repeat(5,1fr)";if(rowSlots.length===1){row.append(document.createElement("div"),document.createElement("div"))}for(const slot of rowSlots){const box=document.createElement("div"),a=map.get(slot);box.className="lineup-position";if(!a)box.classList.add("empty");const r=role(slot);if(a&&(calc.win.t.visualAll||trainRole(r,calc.win.t)>0))box.classList.add(trainRole(r,calc.win.t)>=1||calc.win.t.visualAll?"lineup-position-full":"lineup-position-partial");box.innerHTML=`<div class="lineup-position-name">${slot}</div><div class="lineup-player-name">${a?playerLabel(a.player):""}</div><div class="lineup-player-rating">${a?a.rating.toFixed(2):""}</div>`;row.append(box)}if(rowSlots.length===1){row.append(document.createElement("div"),document.createElement("div"))}pitch.append(row)}el("lineup-warning").hidden=calc.filled.assignments.length>=11}
function renderSubs(calc){const div=el("lineup-substitutes");div.innerHTML="";const labels={GK:"GK",CD:"CD",WB:"WB",IM:"IM",FW:"FW",WG:"WG",AVG:"EX"};for(const s of calc.subs){const box=document.createElement("div");box.className="lineup-position";box.innerHTML=`<div class="lineup-position-name">${labels[s.role]}</div><div class="lineup-player-name">${playerLabel(s.player)}</div><div class="lineup-player-rating">${s.rating.toFixed(2)}</div>`;div.append(box)}}
function renderRecommendations(calc){el("lineup-captain").textContent=calc.cap?playerLabel(calc.cap):"—";el("lineup-set-pieces").textContent=calc.sp?playerLabel(calc.sp):"—";const body=el("lineup-penalty-body");body.innerHTML="";const all=calc.filled.assignments.map(a=>a.player).sort((a,b)=>(fmtNum(b.setPieces)*2+fmtNum(b.scoring)+fmtNum(b.experience)*.25)-(fmtNum(a.setPieces)*2+fmtNum(a.scoring)+fmtNum(a.experience)*.25)||Number(a.playerId)-Number(b.playerId));for(const p of all){const tr=document.createElement("tr");tr.append(td(playerLabel(p)),td(fmtNum(p.setPieces),"number"),td(fmtNum(p.scoring),"number"),td(fmtNum(p.experience),"number"));body.append(tr)}}
function renderDiagnostics(calc){const ex=el("lineup-excluded-body");ex.innerHTML="";if(!calc.elig.excluded.length){const tr=document.createElement("tr");const c=td("No excluded players.");c.colSpan=2;tr.append(c);ex.append(tr)}for(const x of calc.elig.excluded){const tr=document.createElement("tr");tr.append(td(playerLabel(x.p)),td(x.reasons.join(", ")));ex.append(tr)}const eb=el("lineup-eligible-body");eb.innerHTML="";for(const p of calc.elig.eligible){const tr=document.createElement("tr");tr.append(td(playerLabel(p)));for(const key of ["GK","CD","WB","IM","WG","FW","AVG"])tr.append(td(p.ratings[key].toFixed(2),"number"));tr.append(td(fmtNum(p.experience),"number"),td(fmtNum(p.leadership),"number"),td(fmtNum(p.setPieces),"number"));eb.append(tr)}}
function renderCalculation(){current=calculate();renderSelectors(current);renderTables(current);renderPitch(current);renderSubs(current);renderRecommendations(current);renderDiagnostics(current);setVisible(true)}
function matchTypeName(m){return m.matchTypeName||({1:"League",2:"Qualification",3:"Cup",4:"Friendly",5:"Friendly - Cup Rules",7:"Masters"}[m.matchType]||`Type ${m.matchType||"—"}`)}
function renderMatch(m){el("lineup-summary-team-name").textContent=fixtureData?.teamName||sourceData?.teamName||"-";el("lineup-summary-match-name").textContent=m?`${m.homeTeamName||"Home"} vs ${m.awayTeamName||"Away"}`:"-";el("lineup-summary-match-type").textContent=m?matchTypeName(m):"-";el("lineup-summary-training-week-position").textContent=m?.trainingWeekPosition?m.trainingWeekPosition[0].toUpperCase()+m.trainingWeekPosition.slice(1):"-"}
function populateMatches(data){matchSelect.innerHTML="";const matches=data.matches||[];if(!matches.length){const o=document.createElement("option");o.textContent="No upcoming matches returned";matchSelect.append(o);matchSelect.disabled=true;buildBtn.disabled=true;return}for(const m of matches){const o=document.createElement("option");o.value=m.matchId;o.textContent=`${String(m.matchDate||"").slice(0,16)} — ${m.homeTeamName} vs ${m.awayTeamName}`;o.selected=String(m.matchId)===String(data.upcomingMatch?.matchId);matchSelect.append(o)}matchSelect.disabled=false;buildBtn.disabled=false;renderMatch(selectedMatch())}
async function api(teamId,matchId="",mode=""){const u=`/api/lineup?teamId=${encodeURIComponent(teamId)}${matchId?`&matchId=${encodeURIComponent(matchId)}`:""}${mode?`&mode=${encodeURIComponent(mode)}`:""}`,r=await fetch(u,{headers:{Accept:"application/json"}}),d=await r.json();if(!r.ok)throw new Error(d.error||`Server returned ${r.status}`);return d}
async function loadMatches(){const teamId=selectedTeam();if(!validTeam(teamId)||loading)return;loading=true;loadBtn.disabled=true;buildBtn.disabled=true;setVisible(false);setStatus("Loading upcoming matches from Hattrick...");try{fixtureData=await api(teamId,"","matches");populateMatches(fixtureData);setStatus(`Upcoming matches loaded for ${fixtureData.teamName||`TeamID ${teamId}`}.`,"success")}catch(e){setStatus(e.message||"Could not load upcoming matches.","error")}finally{loading=false;loadBtn.disabled=!validTeam(selectedTeam())}}
async function build(){const teamId=selectedTeam(),m=selectedMatch();if(!validTeam(teamId)||!m?.matchId||loading)return;loading=true;buildBtn.disabled=true;trainingOverride="";formationOverride="";setStatus("Loading lineup data and calculating recommendations...");try{sourceData=await api(teamId,m.matchId,"build");renderMatch(sourceData.upcomingMatch);renderCalculation();setStatus("Lineup calculated.","success")}catch(e){setStatus(e.message||"Could not calculate the lineup.","error")}finally{loading=false;buildBtn.disabled=false}}
function resetTeam(id){selectedTeamId=validTeam(id)?String(id):"";fixtureData=sourceData=current=null;trainingOverride=formationOverride="";matchSelect.innerHTML='<option value="">Load matches first</option>';matchSelect.disabled=true;loadBtn.disabled=!selectedTeamId;buildBtn.disabled=true;setVisible(false);renderMatch(null);setStatus(selectedTeamId?"Ready to load upcoming matches.":"Waiting for team data.")}
loadBtn?.addEventListener("click",loadMatches);buildBtn?.addEventListener("click",build);matchSelect?.addEventListener("change",()=>{renderMatch(selectedMatch());setVisible(false);sourceData=current=null;trainingOverride=formationOverride="";buildBtn.disabled=!matchSelect.value;setStatus("Match selected. Click Build Lineup when you are ready.")});trainingSelect?.addEventListener("change",()=>{trainingOverride=trainingSelect.value;formationOverride="";try{renderCalculation()}catch(e){setStatus(e.message,"error")}});formationSelect?.addEventListener("change",()=>{formationOverride=formationSelect.value;try{renderCalculation()}catch(e){setStatus(e.message,"error")}});window.addEventListener("htwb:team-selected",e=>resetTeam(e.detail?.teamId));setTimeout(()=>resetTeam(selectedTeam()),0);
