"use strict";
const htwbRosterStatus=document.getElementById("roster-status"),htwbRosterButton=document.getElementById("roster-rank-button"),htwbRosterResults=document.getElementById("roster-results-section"),htwbRosterTeam=document.getElementById("roster-summary-team"),htwbRosterCount=document.getElementById("roster-summary-count"),htwbRosterDate=document.getElementById("roster-summary-date"),htwbRosterBody=document.getElementById("roster-table-body");
let htwbRosterSelectedTeamId="",htwbRosterLoading=false;
const HTWB_ROSTER_SKILL_K=.12709873475949496,HTWB_ROSTER_SKILL_CURVES={keeper:{a:84.41116904301897,c:-3.013831783094177},defending:{a:166.56004778554478,c:-9.957908611978596},playmaking:{a:136.55214748448975,c:-6.8678322116243695},winger:{a:91.02460134284745,c:-3.4442404158256723},passing:{a:125.20400498385627,c:-6.067538950751518},scoring:{a:143.05562354659511,c:-7.513071982397896},setPieces:{a:26.854610931705555,c:-1.4649057189946455}};
const HTWB_ROSTER_AGE_LINEAR=-125.672885,HTWB_ROSTER_AGE_QUADRATIC=1.83715625,HTWB_ROSTER_AGE_CUBIC=.021044122,HTWB_ROSTER_UNUSED_HALF_LIFE_DAYS=28;
const htwbRosterNum=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const htwbRosterValid=v=>/^\d+$/.test(String(v||""));
function htwbRosterGetTeam(){const current=window.HTWikiBuilder?.getSelectedTeamId?.();return htwbRosterValid(current)?String(current):htwbRosterSelectedTeamId;}
function htwbRosterSetStatus(m,t=""){htwbRosterStatus.textContent=m;htwbRosterStatus.className="builder-status";if(t)htwbRosterStatus.classList.add(`builder-status-${t}`)}
function htwbRosterSelect(id){htwbRosterSelectedTeamId=htwbRosterValid(id)?String(id):"";htwbRosterResults.hidden=true;htwbRosterBody.innerHTML="";htwbRosterButton.disabled=!htwbRosterSelectedTeamId||htwbRosterLoading;htwbRosterSetStatus(htwbRosterSelectedTeamId?"Ready to evaluate the selected roster.":"Waiting for team data.")}
function htwbRosterDateParts(v){if(!v)return null;const s=String(v).replace(" ","T");const d=new Date(/[zZ]|[+-]\d\d:?\d\d$/.test(s)?s:`${s}Z`);return Number.isNaN(d.getTime())?null:{date:d,utc:d.getTime()}}
function htwbRosterDays(a,b){return a&&b?Math.max(0,Math.floor((b.utc-a.utc)/86400000)):0}
function htwbRosterSkill(name,level){const c=HTWB_ROSTER_SKILL_CURVES[name],x=Math.max(0,htwbRosterNum(level));return c?Math.max(0,c.a*(Math.exp(HTWB_ROSTER_SKILL_K*x)-1)+c.c*x):0}
function htwbRosterCurrent(p){return htwbRosterSkill("keeper",p.keeper)+htwbRosterSkill("defending",p.defending)+htwbRosterSkill("playmaking",p.playmaking)+htwbRosterSkill("winger",p.winger)+htwbRosterSkill("passing",p.passing)+htwbRosterSkill("scoring",p.scoring)+htwbRosterSkill("setPieces",p.setPieces)}
function htwbRosterDevelopment(p){const age=htwbRosterNum(p.age)+htwbRosterNum(p.ageDays)/112;if(age>=30)return 0;const t=age-30;return Math.max(0,HTWB_ROSTER_AGE_LINEAR*t+HTWB_ROSTER_AGE_QUADRATIC*t*t+HTWB_ROSTER_AGE_CUBIC*t*t*t)}
function htwbRosterCalc(data){const asOf=htwbRosterDateParts(data.asOfDate||data.fetchedDate||new Date().toISOString())||htwbRosterDateParts(new Date().toISOString());return (data.players||[]).map(p=>{const arrival=htwbRosterDateParts(p.arrivalDate),last=htwbRosterDateParts(p.lastMatchDate),start=[arrival,last].filter(Boolean).sort((a,b)=>b.utc-a.utc)[0]||asOf,unused=htwbRosterDays(start,asOf),current=htwbRosterCurrent(p),dev=htwbRosterDevelopment(p),usage=2**(-unused/HTWB_ROSTER_UNUSED_HALF_LIFE_DAYS),overall=current*usage+dev*usage**2;return {...p,currentValue:current,projectedValue:current+dev,unusedDays:unused,overall,isCoach:String(data.coachId||"")===String(p.playerId||"")}}).sort((a,b)=>a.overall-b.overall||b.unusedDays-a.unusedDays||Number(a.playerId)-Number(b.playerId))}
function htwbRosterFmtDate(v,never=false){if(!v)return never?"Never":"—";const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${Number(m[2])}/${Number(m[3])}/${m[1]}`:String(v)}
function htwbRosterFmtAge(p){return `${htwbRosterNum(p.age)}.${String(Math.floor(htwbRosterNum(p.ageDays)/112*100)).padStart(2,"0")}`}
function htwbRosterFmtNum(v){return Math.round(htwbRosterNum(v)).toLocaleString("en-US")}
function htwbRosterPlayerName(p){const num=Number(p.playerNumber);const prefix=Number.isInteger(num)&&num>=1&&num<=99?`${num} · `:"";return `${prefix}${p.name||`Player ${p.playerId}`}`}
function htwbRosterRender(data,rows){htwbRosterTeam.textContent=data.teamName||`TeamID ${data.teamId||htwbRosterGetTeam()}`;htwbRosterCount.textContent=String(rows.length);htwbRosterDate.textContent=htwbRosterFmtDate(data.asOfDate||data.fetchedDate||new Date().toISOString());htwbRosterBody.innerHTML="";for(const p of rows){const tr=document.createElement("tr");const name=document.createElement("td");name.className="player-number-name";name.textContent=htwbRosterPlayerName(p);if(p.isCoach){const b=document.createElement("span");b.className="coach-badge";b.textContent="COACH";name.append(b)}tr.append(name);const vals=[[htwbRosterFmtAge(p),"number"],[htwbRosterFmtDate(p.lastMatchDate,true),""],[htwbRosterFmtDate(p.arrivalDate),""],[`${p.unusedDays} d`,"number"],[htwbRosterFmtNum(p.currentValue),"number"],[htwbRosterFmtNum(p.projectedValue),"number"],[htwbRosterFmtNum(p.overall),"number"]];for(const [text,cls] of vals){const td=document.createElement("td");td.textContent=text;if(cls)td.className=cls;tr.append(td)}htwbRosterBody.append(tr)}htwbRosterResults.hidden=false;htwbRosterResults.scrollIntoView({behavior:"smooth",block:"start"})}
async function htwbRosterRun(){const teamId=htwbRosterGetTeam();if(!htwbRosterValid(teamId)||htwbRosterLoading)return;htwbRosterLoading=true;htwbRosterButton.disabled=true;htwbRosterSetStatus("Loading roster data from Hattrick...");try{const r=await fetch(`/api/roster?teamId=${encodeURIComponent(teamId)}`,{headers:{Accept:"application/json"}}),d=await r.json();if(!r.ok)throw new Error(d.error||`Server returned ${r.status}`);const rows=htwbRosterCalc(d);htwbRosterRender(d,rows);htwbRosterSetStatus(`Roster evaluated for ${d.teamName||`TeamID ${teamId}`}.`,"success")}catch(e){htwbRosterSetStatus(e.message||"Could not evaluate the roster.","error")}finally{htwbRosterLoading=false;htwbRosterButton.disabled=!htwbRosterValid(htwbRosterGetTeam())}}
htwbRosterButton?.addEventListener("click",htwbRosterRun);window.addEventListener("htwb:team-selected",e=>htwbRosterSelect(e.detail?.teamId));setTimeout(()=>htwbRosterSelect(htwbRosterGetTeam()),0);
