"use strict";
const htwbTeamLoadButton=document.getElementById("load-team-data"),htwbTeamStatus=document.getElementById("team-load-status"),htwbTeamOptions=document.getElementById("wiki-options-section"),htwbTeamOptionList=document.getElementById("team-section-options"),htwbTeamSelectAll=document.getElementById("select-all-sections"),htwbTeamClearAll=document.getElementById("clear-all-sections"),htwbTeamCreate=document.getElementById("create-article"),htwbTeamSelectionStatus=document.getElementById("article-selection-status"),htwbTeamOutputSection=document.getElementById("wiki-output-section"),htwbTeamOutput=document.getElementById("wiki-output"),htwbTeamCopy=document.getElementById("copy-wiki-output"),htwbTeamCopyStatus=document.getElementById("copy-status");
let htwbTeamSelectedId="",htwbTeamData=null,htwbTeamLoading=false;
const HTWB_TEAM_BUILDER_URL="https://ht-wiki-builder.pages.dev/";
const htwbTeamHas=v=>!(v===null||v===undefined||String(v).trim()===""||String(v).toUpperCase()==="NOT AVAILABLE");
const htwbTeamWiki=v=>String(v??"").replace(/[\r\n]+/g," ").replace(/\|/g,"{{!}}").trim();
const htwbTeamNum=v=>Number.isFinite(Number(v))?Number(v).toLocaleString("en-US"):String(v??"");
function htwbTeamDate(v){const m=String(v||"").match(/^(\d{4})-(\d{2})-(\d{2})/);if(!m)return String(v||"");const months=["January","February","March","April","May","June","July","August","September","October","November","December"];return `${Number(m[3])} ${months[Number(m[2])-1]} ${m[1]}`;}
function htwbTeamOrdinal(v){const n=Number(v);if(!Number.isFinite(n)||n<=0)return String(v||"");const m=n%100;if(m>=11&&m<=13)return `${n}th`;return `${n}${n%10===1?"st":n%10===2?"nd":n%10===3?"rd":"th"}`;}
function htwbTeamSelected(){return String(window.HTWikiBuilder?.getSelectedTeamId?.()||htwbTeamSelectedId||"");}
function htwbTeamSetStatus(message,type=""){if(!htwbTeamStatus)return;htwbTeamStatus.hidden=!message;htwbTeamStatus.textContent=message||"";htwbTeamStatus.className="builder-status";if(type)htwbTeamStatus.classList.add(`builder-status-${type}`);}
function htwbTeamReset(id){htwbTeamSelectedId=String(id||"");htwbTeamData=null;if(htwbTeamOptions)htwbTeamOptions.hidden=true;if(htwbTeamOutputSection)htwbTeamOutputSection.hidden=true;if(htwbTeamOptionList)htwbTeamOptionList.innerHTML="";if(htwbTeamOutput)htwbTeamOutput.value="";if(htwbTeamLoadButton)htwbTeamLoadButton.disabled=!htwbTeamSelectedId||htwbTeamLoading;htwbTeamSetStatus(htwbTeamSelectedId?"Ready. Click Load Team Data.":"Waiting for team data.");}
function htwbTeamUsername(){return String(document.getElementById("htwiki-username")?.value||"").replace(/^User\s*:/i,"").trim();}
function htwbTeamChecked(id){return Boolean(document.getElementById(id)?.checked);}
function htwbTeamManager(data){const name=htwbTeamWiki(data.managerName);const user=htwbTeamUsername();return user?`[[User:${htwbTeamWiki(user)}|${name}]]`:name;}
function htwbTeamInfobox(data){if(!data.teamName)return"";const lines=["{{Infobox club"];const add=(k,v)=>{if(htwbTeamHas(v))lines.push(`| ${k.padEnd(15," ")} = ${v}`)};add("teamname",htwbTeamWiki(data.teamName));add("teamid",data.teamId);add("manager",htwbTeamManager(data));add("shortname",htwbTeamWiki(data.shortTeamName));add("region",htwbTeamWiki(data.region));add("country",htwbTeamWiki(data.country));add("league",htwbTeamWiki(data.league));add("league-pos",data.leaguePosition?htwbTeamOrdinal(data.leaguePosition):"");add("arena",htwbTeamWiki(data.arena?.name||data.arenaName));add("capacity",data.arena?.capacity||data.arenaCapacity?htwbTeamNum(data.arena?.capacity||data.arenaCapacity):"");add("coach",htwbTeamWiki(data.coach?.name||data.coachName));add("fanclub",htwbTeamWiki(data.fanclub?.name||data.fanclubName));add("fanclub-size",data.fanclub?.size?htwbTeamNum(data.fanclub.size):"");if(htwbTeamChecked("include-team-logo")&&data.logoUrl)add("logo",`[[File:${data.teamId}.png|210px]]`);const kits=[];if(htwbTeamChecked("include-home-kit"))kits.push(`[[File:${data.teamId}_home.png|120px]]`);if(htwbTeamChecked("include-away-kit"))kits.push(`[[File:${data.teamId}_away.png|120px]]`);if(htwbTeamChecked("include-third-kit"))kits.push(`[[File:${data.teamId}_third.png|${kits.length>=2?80:120}px]]`);if(kits.length)add("kit",kits.join(" "));if(htwbTeamChecked("include-current-season-link")&&data.currentSeason)add("current-season",`[[${htwbTeamWiki(data.teamName)}/Season ${data.currentSeason}|Season ${data.currentSeason}]]`);lines.push("}}");return lines.join("\n");}
function htwbTeamIntro(data){let t=`'''${htwbTeamWiki(data.teamName)}''' is a Hattrick club`;if(data.region&&data.country)t+=` based in [[${htwbTeamWiki(data.region)}]], [[${htwbTeamWiki(data.country)}]]`;else if(data.country)t+=` based in [[${htwbTeamWiki(data.country)}]]`;if(data.managerName)t+=`, managed by ${htwbTeamManager(data)}`;return t+".";}
function htwbTeamInformation(data){return [htwbTeamInfobox(data),htwbTeamIntro(data)].filter(Boolean).join("\n\n");}
function htwbTeamHistory(data){const h=Array.isArray(data.history)?data.history:[];if(!h.length&&!data.activationDate)return"";const lines=["== History ==",""];if(data.activationDate)lines.push(`The current manager's Hattrick tenure began on ${htwbTeamDate(data.activationDate)}.`);for(const x of h)lines.push(`* ${htwbTeamWiki(typeof x==="string"?x:x.text||x.description||"")}`);return lines.join("\n");}
function htwbTeamArena(data){const a=data.arena||{};const name=a.name||data.arenaName;if(!name)return"";let s=`== Arena ==\n\n'''${htwbTeamWiki(name)}''' is the club's home arena.`;const cap=a.capacity||data.arenaCapacity;if(cap)s+=` It has a current capacity of ${htwbTeamNum(cap)}.`;return s;}
function htwbTeamSupporters(data){const f=data.fanclub||{};const name=f.name||data.fanclubName,size=f.size;if(!name&&!size)return"";return `== Supporters ==\n\n${name?`The club's fan club is '''${htwbTeamWiki(name)}'''`:"The club has a registered fan club"}${size?`, with ${htwbTeamNum(size)} members`:""}.`;}
function htwbTeamSquad(data){const p=Array.isArray(data.players)?data.players:[];if(!p.length)return"";const lines=["== Current squad ==","",'{| class="wikitable"',"! No. !! Player !! Nationality !! Age !! Apps !! Goals"];for(const x of p){lines.push("|-",`| ${htwbTeamHas(x.number)?x.number:"—"} || ${htwbTeamWiki(x.name)} || ${htwbTeamWiki(x.nationality||"")} || ${htwbTeamWiki(x.age||"")} || ${htwbTeamHas(x.matches)?x.matches:"—"} || ${htwbTeamHas(x.goals)?x.goals:"—"}`)}lines.push("|}");return lines.join("\n");}
function htwbTeamStaff(data){const coach=data.coach||{name:data.coachName};const staff=Array.isArray(data.staff)?data.staff:[];if(!coach.name&&!staff.length)return"";const lines=["== Team staff ==","",'{| class="wikitable"',"! Role !! Name / Count"];if(coach.name)lines.push("|-",`| Head coach || ${htwbTeamWiki(coach.name)}`);for(const x of staff)if(x.role&&htwbTeamHas(x.count))lines.push("|-",`| ${htwbTeamWiki(x.role)} || ${htwbTeamNum(x.count)}`);lines.push("|}");return lines.join("\n");}
function htwbTeamHonours(data){const h=Array.isArray(data.honours)?data.honours:Array.isArray(data.honors)?data.honors:[];if(!h.length)return"";return ["== Honours ==","",...h.map(x=>`* ${htwbTeamWiki(typeof x==="string"?x:x.name||x.result||"")}`)].join("\n");}
function htwbTeamSeason(data){const r=Array.isArray(data.seasonResults)?data.seasonResults:[];if(!r.length)return"";const lines=["== Season-by-season results ==","",'{| class="wikitable"',"! Season !! League !! Finish !! Cup"];for(const x of r){let season=htwbTeamWiki(x.season||"");if(season&&htwbTeamChecked("include-season-links"))season=`[[${htwbTeamWiki(data.teamName)}/Season ${season}|${season}]]`;lines.push("|-",`| ${season||"—"} || ${htwbTeamWiki(x.series||x.league||"")||"—"} || ${htwbTeamWiki(x.finish||"")||"—"} || ${htwbTeamWiki(x.national||x.cup||"")||"—"}`)}lines.push("|}");return lines.join("\n");}
function htwbTeamHall(data){const r=Array.isArray(data.hallOfFame)?data.hallOfFame:[];if(!r.length)return"";return ["== Hall of Fame ==","",...r.map(x=>`* ${htwbTeamWiki(typeof x==="string"?x:x.name||"")}`)].join("\n");}
function htwbTeamFlags(data){const r=Array.isArray(data.flagCollection)?data.flagCollection:[];if(!r.length)return"";return ["== Flag collection ==","",...r.map(x=>`* ${htwbTeamWiki(typeof x==="string"?x:x.name||"")}`)].join("\n");}
function htwbTeamLinks(data){const l=["== External links ==","",`* [${HTWB_TEAM_BUILDER_URL} This article was generated using HT Wiki Builder]`];if(data.homePage)l.push(`* [${String(data.homePage).replace(/\]/g,"%5D")} Official team website]`);return l.join("\n");}
const htwbTeamSections=[
 {key:"intro",label:"Intro",description:"Article opening, team infobox and introductory paragraph.",build:htwbTeamInformation,available:d=>Boolean(d.teamName),options:"intro"},
 {key:"history",label:"History",description:"Available club history from the current manager's tenure.",build:htwbTeamHistory},
 {key:"arena",label:"Arena",description:"Home arena and available seating capacity details.",build:htwbTeamArena},
 {key:"supporters",label:"Supporters",description:"Fan club name and size when available.",build:htwbTeamSupporters},
 {key:"squad",label:"Current Squad",description:"Current player list and available public match statistics.",build:htwbTeamSquad},
 {key:"staff",label:"Team Staff",description:"Head coach and available specialist staff counts.",build:htwbTeamStaff},
 {key:"honours",label:"Honours",description:"Available competition honours earned by the club.",build:htwbTeamHonours},
 {key:"season",label:"Season-by-Season Results",description:"Available historical season results.",build:htwbTeamSeason,options:"season"},
 {key:"hall",label:"Hall of Fame",description:"Hall of Fame entries when available.",build:htwbTeamHall},
 {key:"flags",label:"Flag Collection",description:"Flag collection data when available.",build:htwbTeamFlags},
 {key:"links",label:"External Links",description:"External links and generator attribution.",build:htwbTeamLinks,available:()=>true}
];
function htwbTeamAvailable(def){return typeof def.available==="function"?Boolean(def.available(htwbTeamData)):Boolean(def.build(htwbTeamData));}
function htwbTeamRenderOptions(){htwbTeamOptionList.innerHTML="";for(const def of htwbTeamSections){const available=htwbTeamAvailable(def),card=document.createElement("div");card.className=`team-section-option${available?"":" team-section-option-disabled"}`;const label=document.createElement("label");label.className="team-section-option-header";const input=document.createElement("input");input.type="checkbox";input.checked=available;input.disabled=!available;input.dataset.section=def.key;const copy=document.createElement("span");copy.className="team-section-option-copy";copy.innerHTML=`<strong>${def.label}</strong><span>${available?def.description:"No usable data available"}</span>`;label.append(input,copy);card.append(label);if(def.options&&available){const fs=document.createElement("fieldset");fs.className="team-section-suboptions";if(def.options==="intro")fs.innerHTML=`<label>HT-Wiki username (optional)<br><input id="htwiki-username" class="team-wiki-input" type="text" autocomplete="off"></label><label><input id="include-team-logo" type="checkbox" ${htwbTeamData.logoUrl?"checked":""} ${htwbTeamData.logoUrl?"":"disabled"}> Include team logo</label><label><input id="include-home-kit" type="checkbox" checked> Include home kit</label><label><input id="include-away-kit" type="checkbox" checked> Include away kit</label><label><input id="include-third-kit" type="checkbox"> Include third kit</label><label><input id="include-current-season-link" type="checkbox" ${htwbTeamData.currentSeason?"":"disabled"}> Link to current team season page</label>`;else fs.innerHTML=`<label><input id="include-season-links" type="checkbox"> Link seasons to individual team season pages</label>`;card.append(fs)}htwbTeamOptionList.append(card)}htwbTeamSync();}
function htwbTeamSync(){const checks=[...htwbTeamOptionList.querySelectorAll("input[data-section]")];const selected=checks.filter(x=>x.checked&&!x.disabled).length,available=checks.filter(x=>!x.disabled).length;htwbTeamCreate.disabled=!selected;htwbTeamSelectionStatus.textContent=selected?`${selected} of ${available} available sections selected.`:`No sections selected. ${available} sections are available.`;for(const x of checks){const fs=x.closest(".team-section-option")?.querySelector("fieldset");if(fs)fs.disabled=!x.checked}}
function htwbTeamArticle(){return htwbTeamSections.filter(def=>document.querySelector(`input[data-section="${def.key}"]`)?.checked).map(def=>def.build(htwbTeamData)).filter(Boolean).join("\n\n");}
async function htwbTeamLoad(){const id=htwbTeamSelected();if(!/^\d+$/.test(id)||htwbTeamLoading)return;htwbTeamLoading=true;htwbTeamLoadButton.disabled=true;htwbTeamSetStatus("Loading available club data from Hattrick...");try{const r=await fetch(`/api/team?teamId=${encodeURIComponent(id)}`,{headers:{Accept:"application/json"}}),d=await r.json();if(!r.ok)throw new Error(d.error||`Server returned ${r.status}`);if(htwbTeamSelected()!==id)return;htwbTeamData=d;htwbTeamSetStatus(`Team data loaded for ${d.teamName||`TeamID ${id}`}.`,"success");htwbTeamOptions.hidden=false;htwbTeamOutputSection.hidden=true;htwbTeamRenderOptions();htwbTeamOptions.scrollIntoView({behavior:"smooth",block:"start"});}catch(e){htwbTeamSetStatus(e.message||"Could not load team data from Hattrick.","error");}finally{htwbTeamLoading=false;htwbTeamLoadButton.disabled=!/^\d+$/.test(htwbTeamSelected());}}
htwbTeamLoadButton?.addEventListener("click",htwbTeamLoad);htwbTeamOptionList?.addEventListener("change",()=>{htwbTeamSync();htwbTeamOutputSection.hidden=true});htwbTeamSelectAll?.addEventListener("click",()=>{htwbTeamOptionList.querySelectorAll("input[data-section]:not(:disabled)").forEach(x=>x.checked=true);htwbTeamSync()});htwbTeamClearAll?.addEventListener("click",()=>{htwbTeamOptionList.querySelectorAll("input[data-section]:not(:disabled)").forEach(x=>x.checked=false);htwbTeamSync()});htwbTeamCreate?.addEventListener("click",()=>{const m=htwbTeamArticle();if(!m)return;htwbTeamOutput.value=m;htwbTeamOutputSection.hidden=false;htwbTeamOutputSection.scrollIntoView({behavior:"smooth",block:"start"})});htwbTeamCopy?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(htwbTeamOutput.value);htwbTeamCopyStatus.textContent="Copied."}catch{htwbTeamOutput.focus();htwbTeamOutput.select();document.execCommand("copy");htwbTeamCopyStatus.textContent="Copied."}});window.addEventListener("htwb:team-selected",e=>htwbTeamReset(e.detail?.teamId));setTimeout(()=>htwbTeamReset(htwbTeamSelected()),0);
