"use strict";
const q=id=>document.getElementById(id),load=q("load-team-data"),status=q("team-load-status"),options=q("wiki-options-section"),grid=q("team-section-options"),outputSection=q("wiki-output-section"),output=q("wiki-output"),selection=q("article-selection-status");let data=null,loading=false,teamId="";
const defs=[
 {key:"intro",label:"Intro and infobox",desc:"Core team identity, manager, league, stadium and optional images."},
 {key:"squad",label:"Current squad",desc:"Current senior-team player list.",available:d=>d.players?.length},
 {key:"club",label:"Club information",desc:"Stadium, region, coach and fan club information.",available:d=>d.stadium||d.region||d.coach?.name||d.fanclubName},
 {key:"category",label:"Category",desc:"Team category and article navigation."}
];
function selectedId(){return String(window.HTWikiBuilder?.getSelectedTeamId?.()||teamId||"");}
function setStatus(t,type=""){status.textContent=t;status.className="builder-status"+(type?` builder-status-${type}`:"");}
function reset(id){teamId=String(id||"");data=null;options.hidden=true;outputSection.hidden=true;output.value="";load.disabled=!/^\d+$/.test(teamId)||loading;setStatus(teamId?"Ready to load the selected team.":"Waiting for team data.");}
function esc(v){return String(v??"").replace(/\|/g,"{{!}}").trim()} function link(v){v=esc(v);return v?`[[${v}]]`:"";}
function renderOptions(){grid.innerHTML="";for(const d of defs){const available=d.available?!!d.available(data):true;const card=document.createElement("div");card.className="team-section-option";const lab=document.createElement("label");lab.className="team-section-option-header";const cb=document.createElement("input");cb.type="checkbox";cb.dataset.sectionKey=d.key;cb.checked=available;cb.disabled=!available;const copy=document.createElement("span");copy.className="team-section-option-copy";copy.innerHTML=`<strong>${d.label}</strong><span>${available?d.desc:"No data available for this section."}</span>`;lab.append(cb,copy);card.append(lab);if(d.key==="intro"){const sub=document.createElement("div");sub.className="team-section-suboptions";sub.innerHTML=`<label class="team-inline-option">HT-Wiki username <input id="htwiki-username" class="team-wiki-input" placeholder="optional"></label><label class="team-inline-option"><input id="include-team-logo" type="checkbox" ${data.logoUrl?"checked":""} ${data.logoUrl?"":"disabled"}> Include team logo</label><label class="team-inline-option"><input id="include-current-season-link" type="checkbox"> Link to current team season page</label>`;card.append(sub);}grid.append(card);}updateCount();grid.addEventListener("change",updateCount,{once:true});}
function checked(key){return !!grid.querySelector(`[data-section-key="${key}"]:checked`)} function updateCount(){const a=[...grid.querySelectorAll("input[data-section-key]:not(:disabled)")],s=a.filter(x=>x.checked);selection.textContent=`${s.length} of ${a.length} available sections selected.`;}
function intro(){const wikiUser=q("htwiki-username")?.value.trim().replace(/^User:/i,"");const manager=data.managerName?(wikiUser?`[[User:${wikiUser}|${esc(data.managerName)}]]`:esc(data.managerName)):"";const lines=["{{Infobox football club",`| clubname = ${esc(data.teamName)}`,`| teamid = ${data.teamId}`];if(data.country)lines.push(`| country = ${esc(data.country)}`);if(data.region)lines.push(`| region = ${esc(data.region)}`);if(data.league)lines.push(`| league = ${link(data.league)}`);if(data.stadium)lines.push(`| stadium = ${esc(data.stadium)}`);if(manager)lines.push(`| manager = ${manager}`);if(q("include-team-logo")?.checked)lines.push(`| image = ${data.teamId}.png`);lines.push("}}");let text=lines.join("\n");text+=`\n\n'''${esc(data.teamName)}''' {{Teamid|${data.teamId}}} is a Hattrick club${data.country?` in [[${esc(data.country)}]]`:""}.`;if(q("include-current-season-link")?.checked&&data.currentSeason)text+=` The current season page is [[${esc(data.teamName)}/Season ${data.currentSeason}|Season ${data.currentSeason}]].`;return text;}
function squad(){if(!data.players?.length)return "";let t="== Current squad ==\n\n{| class=\"wikitable sortable\"\n! #\n! Player\n! Age\n|-";for(const p of data.players)t+=`\n| ${p.number??"—"}\n| [[${esc(p.name)}]]\n| ${p.age??"—"}\n|-`;return t+"\n|}";}
function club(){const rows=[];if(data.stadium)rows.push(["Stadium",data.stadium]);if(data.region)rows.push(["Region",data.region]);if(data.coach?.name)rows.push(["Coach",data.coach.name]);if(data.fanclubName)rows.push(["Fan club",data.fanclubName]);if(!rows.length)return "";return "== Club information ==\n\n{| class=\"wikitable\"\n"+rows.map(([a,b])=>`|-${""}\n! ${a}\n| ${esc(b)}`).join("\n")+"\n|}";}
function category(){return `__NOTOC__\n[[Category:${esc(data.country||"National")} Teams|${esc(data.teamName)}]]`;}
function build(){const parts=[];if(checked("intro"))parts.push(intro());if(checked("squad"))parts.push(squad());if(checked("club"))parts.push(club());if(checked("category"))parts.push(category());return parts.filter(Boolean).join("\n\n");}
async function loadData(){const id=selectedId();if(!id||loading)return;loading=true;load.disabled=true;setStatus("Loading available club data from Hattrick...");try{const r=await fetch(`/api/team?teamId=${encodeURIComponent(id)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||`Server returned ${r.status}`);if(selectedId()!==id)return;data=d;renderOptions();options.hidden=false;setStatus(`Team data loaded for ${d.teamName}.`,`success`);}catch(e){setStatus(e.message||"Could not load team data.","error");}finally{loading=false;load.disabled=!selectedId();}}
load.addEventListener("click",loadData);q("select-all-sections").addEventListener("click",()=>{grid.querySelectorAll("input[data-section-key]:not(:disabled)").forEach(x=>x.checked=true);updateCount();});q("clear-all-sections").addEventListener("click",()=>{grid.querySelectorAll("input[data-section-key]:not(:disabled)").forEach(x=>x.checked=false);updateCount();});q("create-article").addEventListener("click",()=>{output.value=build();outputSection.hidden=false;outputSection.scrollIntoView({behavior:"smooth"});});q("copy-wiki-output").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(output.value);q("copy-status").textContent="Copied.";}catch{output.select();q("copy-status").textContent="Select the text and copy it manually.";}});window.addEventListener("htwb:team-selected",e=>reset(e.detail.teamId));setTimeout(()=>reset(selectedId()),300);
